services:

  api-assinaturas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-assinaturas-springboot
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bd-assinaturas
    networks:
      - api-assinaturas-network
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: api-assinaturas-postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: bd-assinaturas
      POSTGRES_USER: coti
      POSTGRES_PASSWORD: coti
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api-assinaturas-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: api-assinaturas-pgadmin
    restart: always
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: coti@email.com
      PGADMIN_DEFAULT_PASSWORD: Coti@2026
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - api-assinaturas-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  api-assinaturas-network:
    driver: bridge